"""Stable error and process exit code vocabulary shared by Core and CLI."""
from __future__ import annotations

from enum import IntEnum


class ExitCode(IntEnum):
    SUCCESS = 0
    USAGE = 2
    PLUGIN = 3
    FAILED = 4
    CANCELLED = 130


class ErrorCode:
    INVALID_PARAMS = "INVALID_PARAMS"
    COMMAND_NOT_FOUND = "COMMAND_NOT_FOUND"
    TASK_NOT_FOUND = "TASK_NOT_FOUND"
    RESULT_NOT_FOUND = "RESULT_NOT_FOUND"
    PLUGIN_INVALID = "PLUGIN_INVALID"
    PLUGIN_CONFLICT = "PLUGIN_CONFLICT"
    PLUGIN_INSTALL_FAILED = "PLUGIN_INSTALL_FAILED"
    PLUGIN_PACKAGE_FAILED = "PLUGIN_PACKAGE_FAILED"
    PLUGIN_UNINSTALL_FAILED = "PLUGIN_UNINSTALL_FAILED"
    DEPENDENCY_MISSING = "DEPENDENCY_MISSING"
    LOCK_FAILED = "LOCK_FAILED"
    CORE_EXECUTION_FAILED = "CORE_EXECUTION_FAILED"
    HOST_PROTOCOL_ERROR = "HOST_PROTOCOL_ERROR"
    HOST_RESULT_INVALID = "HOST_RESULT_INVALID"
    HOST_CRASHED = "HOST_CRASHED"
    HOST_INTERRUPTED = "HOST_INTERRUPTED"
    TIMEOUT = "TIMEOUT"
    EXECUTION_FAILED = "EXECUTION_FAILED"
    INVALID_OUTPUT_PATH = "INVALID_OUTPUT_PATH"
    MISSING_OUTPUT_FILE = "MISSING_OUTPUT_FILE"
    OUTPUT_TOO_LARGE = "OUTPUT_TOO_LARGE"
    INTERNAL_ERROR = "INTERNAL_ERROR"


# Kept as a plain dict for compatibility with existing imports.
EXIT_CODES = {
    "success": int(ExitCode.SUCCESS),
    "cancelled": int(ExitCode.CANCELLED),
    "failed": int(ExitCode.FAILED),
}
